### PR TITLE
95 change gag button to haptic

### LINKED ISSUE #95: Change GaG button to haptic

### PR DESCRIPTION
**Pull request by FransBillqvist**
And some more work on Settings WAY OUT OF SCOPE GUILTY AS CHARGED

### CODE REVIEW

**Review by LucBen93 — CHANGES_REQUESTED** [review]
Change file name

**Review by DTSD21 — CHANGES_REQUESTED** [review]
change filename to Haptics?

**Review by Zaai90 — APPROVED** [review]

**Review by DTSD21 — APPROVED** [review]

**Review by DTSD21 — APPROVED** [review]
Nice!

**Review by LucBen93 — APPROVED** [review]
Gh gg wp ty ty

**Pull request merged**
